swagger: "2.0"
info:
  version: 0.0.0
  title: title
  x-WM-API_ID: AUxyFQJScVL_bUvZIJ2w
basePath: /foo/v1
tags:
  - name: PersonController
    description: Exposes APIs to work with Person resource.
    externalDocs:
      description: Find out more about Swagger
      url: "http://foo.bar.io"
paths:
  /persons:
    get:
      tags:
        - PersonController
      description: "Gets `Person` objects.\nOptional query param of **size** determines\nsize of returned array\n"
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            title: ArrayOfPersons
            items:
              type: integer
              format: int32
externalDocs:
  description: Find out more about Swagger
  url: "http://foo.bar.io"
